language: generic
dist: trusty
sudo: required

cache:
  directories:
    - $HOME/.cache/vagga

addons:
  ssh_known_hosts: internal.everypony.ru:142

install:
  - "echo ubuntu-mirror: http://mirrors.us.kernel.org/ubuntu/ > ~/.vagga.yaml"
  - "echo alpine-mirror: http://mirrors.gigenet.com/alpinelinux/ >> ~/.vagga.yaml"
  - "echo cache-dir: ~/.cache/vagga >> ~/.vagga.yaml"
  - "echo travis:100000:65536 | sudo tee /etc/subuid | sudo tee /etc/subgid"
  - sudo apt-get install uidmap -y
  - curl http://files.zerogw.com/vagga/vagga-install-testing.sh | sh

before_deploy:
  - openssl aes-256-cbc -K $encrypted_4f0c9e188a38_key -iv $encrypted_4f0c9e188a38_iv -in deploy/deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa

script:
  - vagga _build app-deploy
  - vagga _build redis-deploy

deploy:
  provider: script
  skip_cleanup: true
  script: ./deploy/script.sh
  on:
    tags: true
